config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  namespace :searches do
    resources :animals, only: :index
  end
  resources :animals, only: %i[index show]
  resources :assign_animals, only: :create

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :owner
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :animals, dependent: :destroy
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.all
  end

  def show
    @animal = Animal.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/assign_animals_controller.rb
class AssignAnimalsController < ApplicationController
  def create
    owner_id = params[:owner_id]
    animal_names = params[:animal_names].split(",")

    owner = Owner.find(owner_id)
    animals = Animal.where(name: animal_names)

    animals.each do |animal|
      animal.update(owner: owner)
    end

    redirect_to root_path, notice: "Pets successfully assigned to #{owner.name}."
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @owners = Owner.all
    @animals = Animal.all
  end
end

app/controllers/searches/animals_controller.rb
class Searches::AnimalsController < ApplicationController
  def index
    query = params[:query]
    animals = Animal.where("name ILIKE ?", "%#{query}%").limit(3)
    render json: animals.pluck(:name)
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assign_animals_helper.rb
module AssignAnimalsHelper
end

app/helpers/custom_form_builder.rb
class CustomFormBuilder < ActionView::Helpers::FormBuilder
  def autocomplete_chip(attribute, url:, placeholder: "Type something...", selected_items: [])
    @template.content_tag :div, data: { controller: "autocomplete-chip", autocomplete_chip_url_value: url }, class: "w-full space-y-2" do
      @template.concat label(attribute)
      @template.concat @template.content_tag(:div, "", id: "autocomplete-chip-chips", data: { autocomplete_chip_target: "chips" } )
      @template.concat(
        text_field(
          attribute,
          class: "h-10 w-full px-2 rounded-md shadow-md text-gray-800",
          data: { action: "input->autocomplete-chip#search", autocomplete_chip_target: "input" },
          autocomplete: "off",
          placeholder: placeholder
        )
      )
      @template.concat @template.content_tag(:div, "", id: "autocomplete-chip-results", class: "hidden bg-white text-black rounded-md shadow-md mt-1 p-2", data: { autocomplete_chip_target: "results" })
      @template.concat hidden_field("#{attribute}_names", value: selected_items.join(','), data: { autocomplete_chip_target: "hidden" })
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/searches/animals_helper.rb
module Searches::AnimalsHelper
end

app/views/animals/index.html.erb
<div class="h-screen w-full">
<span class="text-sm">Back to <%= link_to "Home", root_path, class: "text-teal-600" %></span>
<h1 class="text-3xl font-bold">Animals</h1>
<ul>
  <% @animals.each do |animal| %>
    <li class="hover:text-teal-600 transition-colors">
      <%= link_to animal.name, animal_path(animal.id) %>
    </li>
  <% end %>
</ul>
</div>

app/views/animals/show.html.erb
<div class="h-screen w-full">
<span class="text-sm">Back to <%= link_to "Animals", animals_path, class: "text-teal-600" %></span>
<h1 class="text-3xl font-bold"><%= @animal.name %></h1>
<ul>
  <li>age: <%= @animal.age %></li>
  <li>adopted: <%= @animal.adopted %></li>
  <% if @animal.owner %>
    <li>owner: <%= @animal.owner.name %></li>
  <% end %>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Autocomplete Chips Input" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <main class="h-screen w-full flex flex-col gap-4 items-center justify-center px-12 py-6">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<span>Go to <%= link_to " Animals", animals_path, class: "text-teal-600" %></span>
<%= form_with url: assign_animals_path, method: :post, builder: CustomFormBuilder, class: "max-w-xl w-full flex flex-col space-y-4 p-6 m-4 rounded-md shadow-md bg-teal-800 text-gray-200 text-center" do |f| %>
  <div>
    <h1 class="text-3xl font-bold">Assign Pets to Owners</h1>
    <div class="text-sm text-gray-300">
      <p>Add a pet or list of pets and add an owner.</p>
      <p>Click submit to assign the pets to the listed owner.</p>
    </div>
  </div>

  <div class="flex flex-col gap-4 text-left">
    <%= f.label :owner %>
    <%= f.select :owner_id, @owners.map { |o| [o.name, o.id] }, { include_blank: true }, class: "h-10 w-full p-2 rounded-md shadow-md text-gray-800" %>

    <%= f.autocomplete_chip :animals, url: searches_animals_path, placeholder: "Start typing to search for animals..." %>
  </div>

  <div class="flex justify-center">
    <%= f.submit "Submit", class: "w-full bg-teal-600 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded" %>
  </div>
<% end %>

app/views/shared/_combobox.html.erb
<div class="combobox">
  <%= f.text_field method, id: "#{method}_combobox", data: { controller: "combobox", action: "input->combobox#search", combobox_target: "input", combobox_search_url: search_url } %>
  <turbo-frame id="combobox-results-<%= method %>">
    <ul class="combobox-list" data-combobox-target="results"></ul>
  </turbo-frame>
</div>